name: infinitime_dfu_example
description: Exemple d'utilisation de infinitime_dfu_library.
version: 1.0.0

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  infinitime_dfu_library:
    path: ../
  flutter_reactive_ble: ^5.4.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/firmware/
